### ISSUE TITLE
User profile

### ISSUE THREAD

**Issue by YuechengHao626** [JoyfulfrugalistaTechLaucher/Joyfulfrugalista-web#39]
We want users to be able to view and edit their information, upload an avatar, and have the ledger displayed on the right side of their profile.

User should be able to edit the following information:
- [x] Email (required)
- [x] Name (required)
- [x] ~Monthly Goal (required)~
- [x] Phone (optional)
- [x] Gender (optional)
- [x] Avatar (optional)

Other tasks for profile page
- [x] Save the changed user info
- [x] ~profile page popup menu~

**Comment by Linerre** [comment]
Work in progress: https://github.com/JoyfulfrugalistaTechLaucher/Joyfulfrugalista-web/tree/feature/profile
